In [2]:
import os,glob
import pandas as pd
import numpy as np

In [3]:
current_directory = "/Users/chrissoria/Documents/Research/CADAS_Data_Export"

os.chdir(current_directory)

print(current_directory)

/Users/chrissoria/Documents/Research/CADAS_Data_Export

This is what I want to produce: generate new_string_var = cond(old_numeric_var == 0, "correct", cond(old_numeric_var == 1, "incorrect", ""))

In [6]:
Cog = (
    pd.read_excel("../CADAS/CADAS_DD_V5.xlsx", engine='openpyxl', sheet_name="Cognitive")  # replace with your file path
    .loc[lambda df: df['Field_Type'] == 'Option', ['Field_Type', 'Name', 'Special_Info']]
    .reset_index(drop=True)
)

Cog['Special_Info'] = Cog['Special_Info'].str.lower()
Cog['Name'] = Cog['Name'].str.lower()
Cog['Special_Info'] = Cog['Special_Info'].str.replace(' required', '', case=False)

columns_to_process = ['Field_Type', 'Name', 'Special_Info']

for col in columns_to_process:
    Cog[col] = Cog[col].astype(str).str.strip()
    
Cog['Name_Cap'] = Cog['Name'].str.upper()

split_special_info = Cog['Special_Info'].str.split(',', expand=True)
split_special_info = split_special_info.applymap(lambda x: x.strip() if x is not None else None)

Cog = pd.concat([Cog, split_special_info], axis=1)

Cog = Cog.replace({None: np.nan})

for i in range(0, 6):
    Cog[f'new_column{i}'] = Cog.apply(lambda row: str(f'cond({row["Name"]} ==  {Cog.columns[i+4]}, "{row[i]}", '), axis=1).astype(str)

    Cog['new_combined_column'] = ""

for i in range(0, 6):
    Cog['new_combined_column'] += Cog.apply(lambda row: row[f"new_column{i}"] if 'nan' not in str(row[f"new_column{i}"]).lower() else '', axis=1)
    
Cog["generate"] = Cog.apply(lambda row: f'generate {row["Name_Cap"]} = {row["new_combined_column"]}""))', axis=1)

Cog["generate"] = Cog["generate"].apply(lambda x: x + ")" if "2," in str(x) else x)
Cog["generate"] = Cog["generate"].apply(lambda x: x + ")" if "3," in str(x) else x)
Cog["generate"] = Cog["generate"].apply(lambda x: x + ")" if "4," in str(x) else x)
Cog["generate"] = Cog["generate"].apply(lambda x: x + ")" if "5," in str(x) else x)
Cog["generate"] = Cog["generate"].apply(lambda x: x + ")" if "6," in str(x) else x)
Cog["generate"] = Cog["generate"].apply(lambda x: x + ")" if "7," in str(x) else x)
Cog["generate"] = Cog["generate"].apply(lambda x: x + ")" if "8," in str(x) else x)
Cog["generate"] = Cog["generate"].apply(lambda x: x + ")" if "9," in str(x) else x)
Cog["generate"] = Cog["generate"].apply(lambda x: x + ")" if "10," in str(x) else x)
Cog["generate"] = Cog["generate"].apply(lambda x: x + ")" if "11," in str(x) else x)
Cog["generate"] = Cog["generate"].apply(lambda x: x + ")" if "12," in str(x) else x)
Cog["generate"] = Cog["generate"].apply(lambda x: x + ")" if "13," in str(x) else x)

Cog["drop"] = Cog.apply(lambda row: f'drop {row["Name"]}', axis=1)
Cog["full_instruction"] = Cog.apply(lambda row: f'{row["generate"]}\n\n{row["drop"]}', axis=1)

Cog_file = '../CADAS/recode_files/Cog_to_numeric.txt'
with open(Cog_file, 'w') as f:
    for code_line in Cog['full_instruction']:
        f.write(f"{code_line}\n\n")
        
Cog.head()

,Field_Type,Name,Special_Info,Name_Cap,0,1,2,3,4,5,new_column0,new_combined_column,new_column1,new_column2,new_column3,new_column4,new_column5,generate,drop,full_instruction
0,Option,c_0,"correcto,incorrecto",C_0,correcto,incorrecto,NaN,NaN,NaN,NaN,"cond(c_0 == 0, ""correcto"",","cond(c_0 == 0, ""correcto"", cond(c_0 == 1, ""i...","cond(c_0 == 1, ""incorrecto"",","cond(c_0 == 2, ""nan"",","cond(c_0 == 3, ""nan"",","cond(c_0 == 4, ""nan"",","cond(c_0 == 5, ""nan"",","generate C_0 = cond(c_0 == 0, ""correcto"", con...",drop c_0,"generate C_0 = cond(c_0 == 0, ""correcto"", con..."
1,Option,c_1,"correcto,incorrecto",C_1,correcto,incorrecto,NaN,NaN,NaN,NaN,"cond(c_1 == 0, ""correcto"",","cond(c_1 == 0, ""correcto"", cond(c_1 == 1, ""i...","cond(c_1 == 1, ""incorrecto"",","cond(c_1 == 2, ""nan"",","cond(c_1 == 3, ""nan"",","cond(c_1 == 4, ""nan"",","cond(c_1 == 5, ""nan"",","generate C_1 = cond(c_1 == 0, ""correcto"", con...",drop c_1,"generate C_1 = cond(c_1 == 0, ""correcto"", con..."
2,Option,c_2_p_c,"correcto,incorrecto",C_2_P_C,correcto,incorrecto,NaN,NaN,NaN,NaN,"cond(c_2_p_c == 0, ""correcto"",","cond(c_2_p_c == 0, ""correcto"", cond(c_2_p_c =...","cond(c_2_p_c == 1, ""incorrecto"",","cond(c_2_p_c == 2, ""nan"",","cond(c_2_p_c == 3, ""nan"",","cond(c_2_p_c == 4, ""nan"",","cond(c_2_p_c == 5, ""nan"",","generate C_2_P_C = cond(c_2_p_c == 0, ""correc...",drop c_2_p_c,"generate C_2_P_C = cond(c_2_p_c == 0, ""correc..."
3,Option,c_2_d,"correcto,incorrecto",C_2_D,correcto,incorrecto,NaN,NaN,NaN,NaN,"cond(c_2_d == 0, ""correcto"",","cond(c_2_d == 0, ""correcto"", cond(c_2_d == 1...","cond(c_2_d == 1, ""incorrecto"",","cond(c_2_d == 2, ""nan"",","cond(c_2_d == 3, ""nan"",","cond(c_2_d == 4, ""nan"",","cond(c_2_d == 5, ""nan"",","generate C_2_D = cond(c_2_d == 0, ""correcto"",...",drop c_2_d,"generate C_2_D = cond(c_2_d == 0, ""correcto"",..."
4,Option,c_3,"correcto,incorrecto",C_3,correcto,incorrecto,NaN,NaN,NaN,NaN,"cond(c_3 == 0, ""correcto"",","cond(c_3 == 0, ""correcto"", cond(c_3 == 1, ""i...","cond(c_3 == 1, ""incorrecto"",","cond(c_3 == 2, ""nan"",","cond(c_3 == 3, ""nan"",","cond(c_3 == 4, ""nan"",","cond(c_3 == 5, ""nan"",","generate C_3 = cond(c_3 == 0, ""correcto"", con...",drop c_3,"generate C_3 = cond(c_3 == 0, ""correcto"", con..."

In [7]:
Socio = (
    pd.read_excel("../CADAS/CADAS_DD_V5.xlsx", engine='openpyxl', sheet_name="Sociodemographic")  # replace with your file path
    .loc[lambda df: df['Field_Type'] == 'Option', ['Field_Type', 'Name', 'Special_Info']]
    .reset_index(drop=True)
)

Socio['Special_Info'] = Socio['Special_Info'].str.lower()
Socio['Name'] = Socio['Name'].str.lower()
Socio['Special_Info'] = Socio['Special_Info'].str.replace(' required', '', case=False)

columns_to_process = ['Field_Type', 'Name', 'Special_Info']

for col in columns_to_process:
    Socio[col] = Socio[col].astype(str).str.strip()
    
Socio['Name_Cap'] = Socio['Name'].str.upper()

split_special_info = Socio['Special_Info'].str.split(',', expand=True)
split_special_info = split_special_info.applymap(lambda x: x.strip() if x is not None else None)

Socio = pd.concat([Socio, split_special_info], axis=1)

Socio = Socio.replace({None: np.nan})

for i in range(0, 14):
    Socio[f'new_column{i}'] = Socio.apply(lambda row: str(f'cond({row["Name"]} ==  {Socio.columns[i+4]}, "{row[i]}", '), axis=1).astype(str)

    Socio['new_combined_column'] = ""

for i in range(0, 14):
    Socio['new_combined_column'] += Socio.apply(lambda row: row[f"new_column{i}"] if 'nan' not in str(row[f"new_column{i}"]).lower() else '', axis=1)
    
Socio["generate"] = Socio.apply(lambda row: f'generate {row["Name_Cap"]} = {row["new_combined_column"]}""))', axis=1)

Socio["generate"] = Socio["generate"].apply(lambda x: x + ")" if "2," in str(x) else x)
Socio["generate"] = Socio["generate"].apply(lambda x: x + ")" if "3," in str(x) else x)
Socio["generate"] = Socio["generate"].apply(lambda x: x + ")" if "4," in str(x) else x)
Socio["generate"] = Socio["generate"].apply(lambda x: x + ")" if "5," in str(x) else x)
Socio["generate"] = Socio["generate"].apply(lambda x: x + ")" if "6," in str(x) else x)
Socio["generate"] = Socio["generate"].apply(lambda x: x + ")" if "7," in str(x) else x)
Socio["generate"] = Socio["generate"].apply(lambda x: x + ")" if "8," in str(x) else x)
Socio["generate"] = Socio["generate"].apply(lambda x: x + ")" if "9," in str(x) else x)
Socio["generate"] = Socio["generate"].apply(lambda x: x + ")" if "10," in str(x) else x)
Socio["generate"] = Socio["generate"].apply(lambda x: x + ")" if "11," in str(x) else x)
Socio["generate"] = Socio["generate"].apply(lambda x: x + ")" if "12," in str(x) else x)
Socio["generate"] = Socio["generate"].apply(lambda x: x + ")" if "13," in str(x) else x)

Socio["drop"] = Socio.apply(lambda row: f'drop {row["Name"]}', axis=1)
Socio["full_instruction"] = Socio.apply(lambda row: f'{row["generate"]}\n\n{row["drop"]}', axis=1)

Socio_file = '../CADAS/recode_files/Socio_to_numeric.txt'
with open(Socio_file, 'w') as f:
    for code_line in Socio['full_instruction']:
        f.write(f"{code_line}\n\n")
        
Socio.head()

,Field_Type,Name,Special_Info,Name_Cap,0,1,2,3,4,5,...,new_column7,new_column8,new_column9,new_column10,new_column11,new_column12,new_column13,generate,drop,full_instruction
0,Option,s_1_1_p,"negro(a) ,mulato(a) mezclado(a) o trigueño (bl...",S_1_1_P,negro(a),mulato(a) mezclado(a) o trigueño (blanco o negro),blanco(a),mestizo(a) (indio con blanco),otra,no responde,...,"cond(s_1_1_p == 7, ""nan"",","cond(s_1_1_p == 8, ""nan"",","cond(s_1_1_p == 9, ""nan"",","cond(s_1_1_p == 10, ""nan"",","cond(s_1_1_p == 11, ""nan"",","cond(s_1_1_p == 12, ""nan"",","cond(s_1_1_p == 13, ""nan"",","generate S_1_1_P = cond(s_1_1_p == 0, ""negro(...",drop s_1_1_p,"generate S_1_1_P = cond(s_1_1_p == 0, ""negro(..."
1,Option,s_1_1_d,"negro(a) ,mulato(a),blanco(a) ,indio(a),otra,n...",S_1_1_D,negro(a),mulato(a),blanco(a),indio(a),otra,no responde,...,"cond(s_1_1_d == 7, ""nan"",","cond(s_1_1_d == 8, ""nan"",","cond(s_1_1_d == 9, ""nan"",","cond(s_1_1_d == 10, ""nan"",","cond(s_1_1_d == 11, ""nan"",","cond(s_1_1_d == 12, ""nan"",","cond(s_1_1_d == 13, ""nan"",","generate S_1_1_D = cond(s_1_1_d == 0, ""negro(...",drop s_1_1_d,"generate S_1_1_D = cond(s_1_1_d == 0, ""negro(..."
2,Option,s_1_1_c,"negro(a),blanco(a),mulato(a) / mestizo(a),otra...",S_1_1_C,negro(a),blanco(a),mulato(a) / mestizo(a),otra,no responde,no sabe,...,"cond(s_1_1_c == 7, ""nan"",","cond(s_1_1_c == 8, ""nan"",","cond(s_1_1_c == 9, ""nan"",","cond(s_1_1_c == 10, ""nan"",","cond(s_1_1_c == 11, ""nan"",","cond(s_1_1_c == 12, ""nan"",","cond(s_1_1_c == 13, ""nan"",","generate S_1_1_C = cond(s_1_1_c == 0, ""negro(...",drop s_1_1_c,"generate S_1_1_C = cond(s_1_1_c == 0, ""negro(..."
3,Option,s_2_9,"nunca se ha casado ,casado/union consensual ,v...",S_2_9,nunca se ha casado,casado/union consensual,viudo,divorciado/separado,NaN,NaN,...,"cond(s_2_9 == 7, ""nan"",","cond(s_2_9 == 8, ""nan"",","cond(s_2_9 == 9, ""nan"",","cond(s_2_9 == 10, ""nan"",","cond(s_2_9 == 11, ""nan"",","cond(s_2_9 == 12, ""nan"",","cond(s_2_9 == 13, ""nan"",","generate S_2_9 = cond(s_2_9 == 0, ""nunca se h...",drop s_2_9,"generate S_2_9 = cond(s_2_9 == 0, ""nunca se h..."
4,Option,s_2_11,"agnóstico/ateo ,católico romano ,evangélico / ...",S_2_11,agnóstico/ateo,católico romano,evangélico / pentecostal,otro cristiano,santería,judío,...,"cond(s_2_11 == 7, ""ninguna"",","cond(s_2_11 == 8, ""no responde"",","cond(s_2_11 == 9, ""no sabe"",","cond(s_2_11 == 10, ""nan"",","cond(s_2_11 == 11, ""nan"",","cond(s_2_11 == 12, ""nan"",","cond(s_2_11 == 13, ""nan"",","generate S_2_11 = cond(s_2_11 == 0, ""agnóstic...",drop s_2_11,"generate S_2_11 = cond(s_2_11 == 0, ""agnóstic..."

In [45]:
Infor = (
    pd.read_excel("../CADAS/CADAS_DD_V4.xlsx", engine='openpyxl', sheet_name="Informant")  # replace with your file path
    .loc[lambda df: df['Field_Type'] == 'Option', ['Field_Type', 'Name', 'Special_Info']]
    .reset_index(drop=True)
)

Infor['Special_Info'] = Infor['Special_Info'].str.lower()
Infor['Name'] = Infor['Name'].str.lower()
Infor['Special_Info'] = Infor['Special_Info'].str.replace(' required', '', case=False)

columns_to_process = ['Field_Type', 'Name', 'Special_Info']

for col in columns_to_process:
    Infor[col] = Infor[col].astype(str).str.strip()
    
Infor['Name_Cap'] = Infor['Name'].str.upper()

split_special_info = Infor['Special_Info'].str.split(',', expand=True)
split_special_info = split_special_info.applymap(lambda x: x.strip() if x is not None else None)

Infor = pd.concat([Infor, split_special_info], axis=1)

Infor = Infor.replace({None: np.nan})

for i in range(0, 9):
    Infor[f'new_column{i}'] = Infor.apply(lambda row: str(f'cond({row["Name"]} ==  {Infor.columns[i+4]}, "{row[i]}", '), axis=1).astype(str)

    Infor['new_combined_column'] = ""

for i in range(0, 9):
    Infor['new_combined_column'] += Infor.apply(lambda row: row[f"new_column{i}"] if 'nan' not in str(row[f"new_column{i}"]).lower() else '', axis=1)
    
Infor["generate"] = Infor.apply(lambda row: f'generate {row["Name_Cap"]} = {row["new_combined_column"]}""))', axis=1)

Infor["generate"] = Infor["generate"].apply(lambda x: x + ")" if "2," in str(x) else x)
Infor["generate"] = Infor["generate"].apply(lambda x: x + ")" if "3," in str(x) else x)
Infor["generate"] = Infor["generate"].apply(lambda x: x + ")" if "4," in str(x) else x)
Infor["generate"] = Infor["generate"].apply(lambda x: x + ")" if "5," in str(x) else x)
Infor["generate"] = Infor["generate"].apply(lambda x: x + ")" if "6," in str(x) else x)
Infor["generate"] = Infor["generate"].apply(lambda x: x + ")" if "7," in str(x) else x)
Infor["generate"] = Infor["generate"].apply(lambda x: x + ")" if "8," in str(x) else x)
Infor["generate"] = Infor["generate"].apply(lambda x: x + ")" if "9," in str(x) else x)
Infor["generate"] = Infor["generate"].apply(lambda x: x + ")" if "10," in str(x) else x)
Infor["generate"] = Infor["generate"].apply(lambda x: x + ")" if "11," in str(x) else x)
Infor["generate"] = Infor["generate"].apply(lambda x: x + ")" if "12," in str(x) else x)
Infor["generate"] = Infor["generate"].apply(lambda x: x + ")" if "13," in str(x) else x)

Infor["drop"] = Infor.apply(lambda row: f'drop {row["Name"]}', axis=1)
Infor["full_instruction"] = Infor.apply(lambda row: f'{row["generate"]}\n\n{row["drop"]}', axis=1)

Infor_file = '../CADAS/recode_files/Infor_to_numeric.txt'
with open(Infor_file, 'w') as f:
    for code_line in Infor['generate']:
        f.write(f"{code_line}\n\n")

Infor.head()

,Field_Type,Name,Special_Info,Name_Cap,0,1,2,3,4,5,...,new_column2,new_column3,new_column4,new_column5,new_column6,new_column7,new_column8,generate,drop,full_instruction
0,Option,i_a2,"si,no,no responde,no sabe",I_A2,si,no,no responde,no sabe,NaN,NaN,...,"cond(i_a2 == 2, ""no responde"",","cond(i_a2 == 3, ""no sabe"",","cond(i_a2 == 4, ""nan"",","cond(i_a2 == 5, ""nan"",","cond(i_a2 == 6, ""nan"",","cond(i_a2 == 7, ""nan"",","cond(i_a2 == 8, ""nan"",","generate I_A2 = cond(i_a2 == 0, ""si"", cond(i_...",drop i_a2,"generate I_A2 = cond(i_a2 == 0, ""si"", cond(i_..."
1,Option,i_a3,"si,no,no responde,no sabe",I_A3,si,no,no responde,no sabe,NaN,NaN,...,"cond(i_a3 == 2, ""no responde"",","cond(i_a3 == 3, ""no sabe"",","cond(i_a3 == 4, ""nan"",","cond(i_a3 == 5, ""nan"",","cond(i_a3 == 6, ""nan"",","cond(i_a3 == 7, ""nan"",","cond(i_a3 == 8, ""nan"",","generate I_A3 = cond(i_a3 == 0, ""si"", cond(i_...",drop i_a3,"generate I_A3 = cond(i_a3 == 0, ""si"", cond(i_..."
2,Option,i_a4,"si,no,no responde,no sabe",I_A4,si,no,no responde,no sabe,NaN,NaN,...,"cond(i_a4 == 2, ""no responde"",","cond(i_a4 == 3, ""no sabe"",","cond(i_a4 == 4, ""nan"",","cond(i_a4 == 5, ""nan"",","cond(i_a4 == 6, ""nan"",","cond(i_a4 == 7, ""nan"",","cond(i_a4 == 8, ""nan"",","generate I_A4 = cond(i_a4 == 0, ""si"", cond(i_...",drop i_a4,"generate I_A4 = cond(i_a4 == 0, ""si"", cond(i_..."
3,Option,i_b1,"miembro del hogar de xxxx?,hijo no-residente d...",I_B1,miembro del hogar de xxxx?,hijo no-residente de xxxx?,otro?,NaN,NaN,NaN,...,"cond(i_b1 == 2, ""otro?"",","cond(i_b1 == 3, ""nan"",","cond(i_b1 == 4, ""nan"",","cond(i_b1 == 5, ""nan"",","cond(i_b1 == 6, ""nan"",","cond(i_b1 == 7, ""nan"",","cond(i_b1 == 8, ""nan"",","generate I_B1 = cond(i_b1 == 0, ""miembro del ...",drop i_b1,"generate I_B1 = cond(i_b1 == 0, ""miembro del ..."
4,Option,i_b4,"femenino,masculino,otro",I_B4,femenino,masculino,otro,NaN,NaN,NaN,...,"cond(i_b4 == 2, ""otro"",","cond(i_b4 == 3, ""nan"",","cond(i_b4 == 4, ""nan"",","cond(i_b4 == 5, ""nan"",","cond(i_b4 == 6, ""nan"",","cond(i_b4 == 7, ""nan"",","cond(i_b4 == 8, ""nan"",","generate I_B4 = cond(i_b4 == 0, ""femenino"", c...",drop i_b4,"generate I_B4 = cond(i_b4 == 0, ""femenino"", c..."

In [46]:
Phys = (
    pd.read_excel("../CADAS/CADAS_DD_V4.xlsx", engine='openpyxl', sheet_name="Physical_Exam")  # replace with your file path
    .loc[lambda df: df['Field_Type'] == 'Option', ['Field_Type', 'Name', 'Special_Info']]
    .reset_index(drop=True)
)

Phys['Special_Info'] = Phys['Special_Info'].str.lower()
Phys['Name'] = Phys['Name'].str.lower()
Phys['Special_Info'] = Phys['Special_Info'].str.replace(' required', '', case=False)

columns_to_process = ['Field_Type', 'Name', 'Special_Info']

for col in columns_to_process:
    Phys[col] = Phys[col].astype(str).str.strip()
    
Phys['Name_Cap'] = Phys['Name'].str.upper()

split_special_info = Phys['Special_Info'].str.split(',', expand=True)
split_special_info = split_special_info.applymap(lambda x: x.strip() if x is not None else None)

Phys = pd.concat([Phys, split_special_info], axis=1)

Phys = Phys.replace({None: np.nan})

for i in range(0, 8):
    Phys[f'new_column{i}'] = Phys.apply(lambda row: str(f'cond({row["Name"]} ==  {Phys.columns[i+4]}, "{row[i]}", '), axis=1).astype(str)

    Phys['new_combined_column'] = ""

for i in range(0, 8):
    Phys['new_combined_column'] += Phys.apply(lambda row: row[f"new_column{i}"] if 'nan' not in str(row[f"new_column{i}"]).lower() else '', axis=1)
    
Phys["generate"] = Phys.apply(lambda row: f'generate {row["Name_Cap"]} = {row["new_combined_column"]}""))', axis=1)

Phys["generate"] = Phys["generate"].apply(lambda x: x + ")" if "2," in str(x) else x)
Phys["generate"] = Phys["generate"].apply(lambda x: x + ")" if "3," in str(x) else x)
Phys["generate"] = Phys["generate"].apply(lambda x: x + ")" if "4," in str(x) else x)
Phys["generate"] = Phys["generate"].apply(lambda x: x + ")" if "5," in str(x) else x)
Phys["generate"] = Phys["generate"].apply(lambda x: x + ")" if "6," in str(x) else x)
Phys["generate"] = Phys["generate"].apply(lambda x: x + ")" if "7," in str(x) else x)
Phys["generate"] = Phys["generate"].apply(lambda x: x + ")" if "8," in str(x) else x)
Phys["generate"] = Phys["generate"].apply(lambda x: x + ")" if "9," in str(x) else x)
Phys["generate"] = Phys["generate"].apply(lambda x: x + ")" if "10," in str(x) else x)
Phys["generate"] = Phys["generate"].apply(lambda x: x + ")" if "11," in str(x) else x)
Phys["generate"] = Phys["generate"].apply(lambda x: x + ")" if "12," in str(x) else x)
Phys["generate"] = Phys["generate"].apply(lambda x: x + ")" if "13," in str(x) else x)

Phys["drop"] = Phys.apply(lambda row: f'drop {row["Name"]}', axis=1)
Phys["full_instruction"] = Phys.apply(lambda row: f'{row["generate"]}\n\n{row["drop"]}', axis=1)

Phys_file = '../CADAS/recode_files/Phys_to_numeric.txt'
with open(Phys_file, 'w') as f:
    for code_line in Phys['generate']:
        f.write(f"{code_line}\n\n")

Phys.head()

,Field_Type,Name,Special_Info,Name_Cap,0,1,2,3,4,5,...,new_column1,new_column2,new_column3,new_column4,new_column5,new_column6,new_column7,generate,drop,full_instruction
0,Option,p2_1,"no,si",P2_1,no,si,NaN,NaN,NaN,NaN,...,"cond(p2_1 == 1, ""si"",","cond(p2_1 == 2, ""nan"",","cond(p2_1 == 3, ""nan"",","cond(p2_1 == 4, ""nan"",","cond(p2_1 == 5, ""nan"",","cond(p2_1 == 6, ""nan"",","cond(p2_1 == 7, ""nan"",","generate P2_1 = cond(p2_1 == 0, ""no"", cond(p2...",drop p2_1,"generate P2_1 = cond(p2_1 == 0, ""no"", cond(p2..."
1,Option,p6,"mirada hacia arriba normal,mirada hacia arriba...",P6,mirada hacia arriba normal,mirada hacia arriba limitada,no puede o casi no puede mirar hacia arriba,no hizo la prueba,NaN,NaN,...,"cond(p6 == 1, ""mirada hacia arriba limitada"",","cond(p6 == 2, ""no puede o casi no puede mirar...","cond(p6 == 3, ""no hizo la prueba"",","cond(p6 == 4, ""nan"",","cond(p6 == 5, ""nan"",","cond(p6 == 6, ""nan"",","cond(p6 == 7, ""nan"",","generate P6 = cond(p6 == 0, ""mirada hacia arr...",drop p6,"generate P6 = cond(p6 == 0, ""mirada hacia arr..."
2,Option,p7_1,"1-4 golpes,5 golpes,6-9 golpes,10+ golpes,no i...",P7_1,1-4 golpes,5 golpes,6-9 golpes,10+ golpes,no intentó la prueba,NaN,...,"cond(p7_1 == 1, ""5 golpes"",","cond(p7_1 == 2, ""6-9 golpes"",","cond(p7_1 == 3, ""10+ golpes"",","cond(p7_1 == 4, ""no intentó la prueba"",","cond(p7_1 == 5, ""nan"",","cond(p7_1 == 6, ""nan"",","cond(p7_1 == 7, ""nan"",","generate P7_1 = cond(p7_1 == 0, ""1-4 golpes"",...",drop p7_1,"generate P7_1 = cond(p7_1 == 0, ""1-4 golpes"",..."
3,Option,p7_2,"no hace trompa (protruye los labios),trompa pr...",P7_2,no hace trompa (protruye los labios),trompa presente,no pudo hacerlo,NaN,NaN,NaN,...,"cond(p7_2 == 1, ""trompa presente"",","cond(p7_2 == 2, ""no pudo hacerlo"",","cond(p7_2 == 3, ""nan"",","cond(p7_2 == 4, ""nan"",","cond(p7_2 == 5, ""nan"",","cond(p7_2 == 6, ""nan"",","cond(p7_2 == 7, ""nan"",","generate P7_2 = cond(p7_2 == 0, ""no hace trom...",drop p7_2,"generate P7_2 = cond(p7_2 == 0, ""no hace trom..."
4,Option,p7_3,"no hay contracción facial,reflejo de contracci...",P7_3,no hay contracción facial,reflejo de contracción facial presente,no pudo hacerlo,NaN,NaN,NaN,...,"cond(p7_3 == 1, ""reflejo de contracción facia...","cond(p7_3 == 2, ""no pudo hacerlo"",","cond(p7_3 == 3, ""nan"",","cond(p7_3 == 4, ""nan"",","cond(p7_3 == 5, ""nan"",","cond(p7_3 == 6, ""nan"",","cond(p7_3 == 7, ""nan"",","generate P7_3 = cond(p7_3 == 0, ""no hay contr...",drop p7_3,"generate P7_3 = cond(p7_3 == 0, ""no hay contr..."

In [47]:
Household = (
    pd.read_excel("../CADAS/CADAS_DD_V4.xlsx", engine='openpyxl', sheet_name="Household")  # replace with your file path
    .loc[lambda df: df['Field_Type'] == 'Option', ['Field_Type', 'Name', 'Special_Info']]
    .reset_index(drop=True)
)

Household['Special_Info'] = Household['Special_Info'].str.lower()
Household['Name'] = Household['Name'].str.lower()
Household['Special_Info'] = Household['Special_Info'].str.replace(' required', '', case=False)

columns_to_process = ['Field_Type', 'Name', 'Special_Info']

for col in columns_to_process:
    Household[col] = Household[col].astype(str).str.strip()
    
Household['Name_Cap'] = Household['Name'].str.upper()

split_special_info = Household['Special_Info'].str.split(',', expand=True)
split_special_info = split_special_info.applymap(lambda x: x.strip() if x is not None else None)

Household = pd.concat([Household, split_special_info], axis=1)

Household = Household.replace({None: np.nan})

for i in range(0, 8):
    Household[f'new_column{i}'] = Household.apply(lambda row: str(f'cond({row["Name"]} ==  {Household.columns[i+4]}, "{row[i]}", '), axis=1).astype(str)

    Household['new_combined_column'] = ""

for i in range(0, 8):
    Household['new_combined_column'] += Household.apply(lambda row: row[f"new_column{i}"] if 'nan' not in str(row[f"new_column{i}"]).lower() else '', axis=1)
    
Household["generate"] = Household.apply(lambda row: f'generate {row["Name_Cap"]} = {row["new_combined_column"]}""))', axis=1)

Household["generate"] = Household["generate"].apply(lambda x: x + ")" if "2," in str(x) else x)
Household["generate"] = Household["generate"].apply(lambda x: x + ")" if "3," in str(x) else x)
Household["generate"] = Household["generate"].apply(lambda x: x + ")" if "4," in str(x) else x)
Household["generate"] = Household["generate"].apply(lambda x: x + ")" if "5," in str(x) else x)
Household["generate"] = Household["generate"].apply(lambda x: x + ")" if "6," in str(x) else x)
Household["generate"] = Household["generate"].apply(lambda x: x + ")" if "7," in str(x) else x)
Household["generate"] = Household["generate"].apply(lambda x: x + ")" if "8," in str(x) else x)
Household["generate"] = Household["generate"].apply(lambda x: x + ")" if "9," in str(x) else x)
Household["generate"] = Household["generate"].apply(lambda x: x + ")" if "10," in str(x) else x)
Household["generate"] = Household["generate"].apply(lambda x: x + ")" if "11," in str(x) else x)
Household["generate"] = Household["generate"].apply(lambda x: x + ")" if "12," in str(x) else x)
Household["generate"] = Household["generate"].apply(lambda x: x + ")" if "13," in str(x) else x)

Household["drop"] = Household.apply(lambda row: f'drop {row["Name"]}', axis=1)
Household["full_instruction"] = Household.apply(lambda row: f'{row["generate"]}\n\n{row["drop"]}', axis=1)


Household_file = '../CADAS/recode_files/Household_to_numeric.txt'
with open(Household_file, 'w') as f:
    for code_line in Household['generate']:
        f.write(f"{code_line}\n\n")

Household.head()

,Field_Type,Name,Special_Info,Name_Cap,0,1,2,3,4,5,...,new_column1,new_column2,new_column3,new_column4,new_column5,new_column6,new_column7,generate,drop,full_instruction
0,Option,h_3_1,"propietario ,alquilada ,otro",H_3_1,propietario,alquilada,otro,NaN,NaN,NaN,...,"cond(h_3_1 == 1, ""alquilada"",","cond(h_3_1 == 2, ""otro"",","cond(h_3_1 == 3, ""nan"",","cond(h_3_1 == 4, ""nan"",","cond(h_3_1 == 5, ""nan"",","cond(h_3_1 == 6, ""nan"",","cond(h_3_1 == 7, ""nan"",","generate H_3_1 = cond(h_3_1 == 0, ""propietari...",drop h_3_1,"generate H_3_1 = cond(h_3_1 == 0, ""propietari..."
1,Option,h_3_3a_p,"si,no,no responde,no sabe",H_3_3A_P,si,no,no responde,no sabe,NaN,NaN,...,"cond(h_3_3a_p == 1, ""no"",","cond(h_3_3a_p == 2, ""no responde"",","cond(h_3_3a_p == 3, ""no sabe"",","cond(h_3_3a_p == 4, ""nan"",","cond(h_3_3a_p == 5, ""nan"",","cond(h_3_3a_p == 6, ""nan"",","cond(h_3_3a_p == 7, ""nan"",","generate H_3_3A_P = cond(h_3_3a_p == 0, ""si"",...",drop h_3_3a_p,"generate H_3_3A_P = cond(h_3_3a_p == 0, ""si"",..."
2,Option,h_3_3a_d,"si,no,no responde,no sabe",H_3_3A_D,si,no,no responde,no sabe,NaN,NaN,...,"cond(h_3_3a_d == 1, ""no"",","cond(h_3_3a_d == 2, ""no responde"",","cond(h_3_3a_d == 3, ""no sabe"",","cond(h_3_3a_d == 4, ""nan"",","cond(h_3_3a_d == 5, ""nan"",","cond(h_3_3a_d == 6, ""nan"",","cond(h_3_3a_d == 7, ""nan"",","generate H_3_3A_D = cond(h_3_3a_d == 0, ""si"",...",drop h_3_3a_d,"generate H_3_3A_D = cond(h_3_3a_d == 0, ""si"",..."
3,Option,h_3_3a_c,"si,no,no responde,no sabe",H_3_3A_C,si,no,no responde,no sabe,NaN,NaN,...,"cond(h_3_3a_c == 1, ""no"",","cond(h_3_3a_c == 2, ""no responde"",","cond(h_3_3a_c == 3, ""no sabe"",","cond(h_3_3a_c == 4, ""nan"",","cond(h_3_3a_c == 5, ""nan"",","cond(h_3_3a_c == 6, ""nan"",","cond(h_3_3a_c == 7, ""nan"",","generate H_3_3A_C = cond(h_3_3a_c == 0, ""si"",...",drop h_3_3a_c,"generate H_3_3A_C = cond(h_3_3a_c == 0, ""si"",..."
4,Option,h_3_3b_p,"si,no,no responde,no sabe",H_3_3B_P,si,no,no responde,no sabe,NaN,NaN,...,"cond(h_3_3b_p == 1, ""no"",","cond(h_3_3b_p == 2, ""no responde"",","cond(h_3_3b_p == 3, ""no sabe"",","cond(h_3_3b_p == 4, ""nan"",","cond(h_3_3b_p == 5, ""nan"",","cond(h_3_3b_p == 6, ""nan"",","cond(h_3_3b_p == 7, ""nan"",","generate H_3_3B_P = cond(h_3_3b_p == 0, ""si"",...",drop h_3_3b_p,"generate H_3_3B_P = cond(h_3_3b_p == 0, ""si"",..."